/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package net.i2p.router.web.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import net.i2p.router.web.helpers.SummaryHelper;

public final class logs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/xhr1.jsi", Long.valueOf(1607264743000L));
    _jspx_dependants.put("/summarynoframe.jsi", Long.valueOf(1607264743000L));
    _jspx_dependants.put("/summary.jsi", Long.valueOf(1607264743000L));
    _jspx_dependants.put("/summaryajax.jsi", Long.valueOf(1607264743000L));
    _jspx_dependants.put("/css.jsi", Long.valueOf(1607264743000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("net.i2p.router.web.helpers.SummaryHelper");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n<html><head>\n");

   /*
    * This should be included inside <head>...</head>,
    * as it sets the stylesheet.
    *
    * This is included almost 30 times, so keep whitespace etc. to a minimum.
    */

   // http://www.crazysquirrel.com/computing/general/form-encoding.jspx
   if (request.getCharacterEncoding() == null)
       request.setCharacterEncoding("UTF-8");

   // Now that we use POST for most forms, these prevent the back button from working after a form submit
   // Just let the browser do its thing
   //response.setHeader("Pragma", "no-cache");
   //response.setHeader("Cache-Control","no-cache");
   //response.setDateHeader("Expires", 0);

   // the above will b0rk if the servlet engine has already flushed
   // the response prior to including this file, so it should be
   // near the top

   String i2pcontextId = request.getParameter("i2p.contextId");
   try {
       if (i2pcontextId != null) {
           session.setAttribute("i2p.contextId", i2pcontextId);
       } else {
           i2pcontextId = (String) session.getAttribute("i2p.contextId");
       }
   } catch (IllegalStateException ise) {}


      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      net.i2p.router.web.CSSHelper intl = null;
      intl = (net.i2p.router.web.CSSHelper) _jspx_page_context.getAttribute("intl", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (intl == null){
        intl = new net.i2p.router.web.CSSHelper();
        _jspx_page_context.setAttribute("intl", intl, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("intl"), "contextId",
i2pcontextId);


   // used several times below
   String theUserAgent = request.getHeader("User-Agent");
   String theThemePath = intl.getTheme(theUserAgent);


      out.write("<link rel=\"icon\" href=\"");
      out.print(theThemePath);
      out.write("images/favicon.ico\">");

   response.setHeader("Accept-Ranges", "none");

   String cspNonce = Integer.toHexString(net.i2p.util.RandomSource.getInstance().nextInt());

   // clickjacking
   if (intl.shouldSendXFrame()) {
      response.setHeader("X-Frame-Options", "SAMEORIGIN");
      // unsafe-inline is a fallback for browsers not supporting nonce
      // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
      response.setHeader("Content-Security-Policy", "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'nonce-" + cspNonce + "'; form-action 'self'; frame-ancestors 'self'; object-src 'none'; media-src 'none'");
      response.setHeader("X-XSS-Protection", "1; mode=block");
      response.setHeader("X-Content-Type-Options", "nosniff");
   }
   // https://www.w3.org/TR/referrer-policy/
   // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
   // As of Chrome 56, Firefox 50, Opera 43. "same-origin" not widely supported.
   response.setHeader("Referrer-Policy", "no-referrer");

   String conNonceParam = request.getParameter("consoleNonce");
   if (net.i2p.router.web.CSSHelper.getNonce().equals(conNonceParam)) {
       intl.setLang(request.getParameter("lang"));
       intl.setNews(request.getParameter("news"));
   }

      out.write("<link href=\"");
      out.print(theThemePath);
      out.write("console.css?");
      out.print(net.i2p.CoreVersion.VERSION);
      out.write("\" rel=\"stylesheet\" type=\"text/css\">\n");

   if (intl.getLang().equals("zh")) {
       // make the fonts bigger for chinese

      out.write("<link href=\"");
      out.print(theThemePath);
      out.write("console_big.css?");
      out.print(net.i2p.CoreVersion.VERSION);
      out.write("\" rel=\"stylesheet\" type=\"text/css\">\n");

   } else if (intl.getLang().equals("ar")) {
       // Use RTL theme for Arabic

      out.write("<link href=\"");
      out.print(theThemePath);
      out.write("console_ar.css?");
      out.print(net.i2p.CoreVersion.VERSION);
      out.write("\" rel=\"stylesheet\" type=\"text/css\">\n");

   }
   if (!intl.allowIFrame(theUserAgent)) {

      out.write("<meta name=\"viewport\" content=\"width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;\" />\n<link href=\"");
      out.print(theThemePath);
      out.write("mobile.css?");
      out.print(net.i2p.CoreVersion.VERSION);
      out.write("\" rel=\"stylesheet\" type=\"text/css\">\n");

   }

      out.write('\n');
      out.write('\n');
      out.print(intl.title("logs"));
      out.write('\n');

    if (!intl.getDisableRefresh()) {

      out.write("<script src=\"/js/ajax.js?");
      out.print(net.i2p.CoreVersion.VERSION);
      out.write("\" type=\"text/javascript\"></script>\n<script nonce=\"");
      out.print(cspNonce);
      out.write("\" type=\"text/javascript\">\n/* @license http://creativecommons.org/publicdomain/zero/1.0/legalcode CC0-1.0 */\n\n  var failMessage = \"<hr><b>");
      out.print(intl._t("Router is down"));
      out.write("<\\/b>\";\n  function requestAjax1() { ajax(\"/xhr1.jsp?requestURI=");
      out.print(request.getRequestURI());
      out.write("\", \"xhr\", ");
      out.print(intl.getRefresh());
      out.write("000); }\n  function initAjax() { setTimeout(requestAjax1, ");
      out.print(intl.getRefresh());
      out.write("000);  }\n  initAjax();\n\n/* @license-end */\n</script>");

    }

      out.write('\n');
      out.write("\n</head><body>\n");
      net.i2p.router.web.NewsHelper newshelper = null;
      newshelper = (net.i2p.router.web.NewsHelper) _jspx_page_context.getAttribute("newshelper", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (newshelper == null){
        newshelper = new net.i2p.router.web.NewsHelper();
        _jspx_page_context.setAttribute("newshelper", newshelper, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("newshelper"), "contextId",
i2pcontextId);
      out.write('\n');

    java.io.File newspath = new java.io.File(net.i2p.I2PAppContext.getGlobalContext().getRouterDir(), "docs/news.xml");

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("newshelper"), "page",
newspath.getAbsolutePath());
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("newshelper"), "maxLines", "300", null, null, false);
      out.write("\n<div class=\"routersummaryouter\">\n");

    // The refresh delay, 0 to disable
    String d = "0";
    boolean allowIFrame = intl.allowIFrame(request.getHeader("User-Agent"));
    if (allowIFrame) {
        // skip the iframe if refresh disabled
        d = request.getParameter("refresh");
        String newDelay = "";
        if (d == null || "".equals(d))
            d = intl.getRefresh();
        else {
            long delay;
            try {
                delay = Long.parseLong(d);
            } catch (NumberFormatException nfe) {
                delay = 60;
            }
            // pass the new delay parameter to the iframe
            newDelay = "?refresh=" + delay;
            // update disable boolean
            intl.setDisableRefresh(d);
        }
        if (false && !intl.getDisableRefresh())
            out.print("<noscript><iframe src=\"/summaryframe.jsp" + newDelay + "\" height=\"1500\" width=\"200\" scrolling=\"auto\" frameborder=\"0\" title=\"sidepanel\"></noscript>\n");
    }

      out.write("\n<div class=\"routersummary\">\n");

    if (allowIFrame) {
        // Display the whole summary bar

      out.write('\n');

/*
 * TODO - the bar would render more cleanly if we specified the img height and width here,
 * but unfortunately the images in the different themes are different sizes.
 * They range in height from 37 to 43 px. But there's a -2 bottom margin...
 * So put it in a div.
 */

      out.write("\n  <div>\n   <a href=\"/\" target=\"_top\">\n    <img src=\"");
      out.print(intl.getTheme(request.getHeader("User-Agent")));
      out.write("images/i2plogo.png\" alt=\"");
      out.print(intl._t("I2P Router Console"));
      out.write("\" title=\"");
      out.print(intl._t("I2P Router Console"));
      out.write("\">\n   </a>\n  </div>\n  <div id=\"xhr\">\n<!-- for non-script -->\n");

/*
 * Note:
 * This is included on every refresh, so keep whitespace etc. to a minimum.
 */

      net.i2p.router.web.helpers.SummaryHelper helper = null;
      helper = (net.i2p.router.web.helpers.SummaryHelper) _jspx_page_context.getAttribute("helper", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (helper == null){
        helper = new net.i2p.router.web.helpers.SummaryHelper();
        _jspx_page_context.setAttribute("helper", helper, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("helper"), "contextId",
i2pcontextId);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("helper"), "action",
request.getParameter("action"));
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("helper"), "updateNonce",
request.getParameter("updateNonce"));
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("helper"), "consoleNonce",
request.getParameter("consoleNonce"));

    String reqURI = request.getRequestURI();
    if (reqURI.contains("/xhr1"))
        reqURI = request.getParameter("requestURI");
    helper.setRequestURI(reqURI);
    helper.storeWriter(out);
    helper.storeNewsHelper(newshelper);
/*
 * The following is required for the reseed button to work, although we probably
 * only need the reseedNonce property.
 */

      net.i2p.router.web.helpers.ReseedHandler reseed = null;
      reseed = (net.i2p.router.web.helpers.ReseedHandler) _jspx_page_context.getAttribute("reseed", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (reseed == null){
        reseed = new net.i2p.router.web.helpers.ReseedHandler();
        _jspx_page_context.setAttribute("reseed", reseed, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("reseed"), request);

/*
 * The following is required for the update buttons to work, although we probably
 * only need the updateNonce property.
 */

      net.i2p.router.web.UpdateHandler update = null;
      update = (net.i2p.router.web.UpdateHandler) _jspx_page_context.getAttribute("update", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (update == null){
        update = new net.i2p.router.web.UpdateHandler();
        _jspx_page_context.setAttribute("update", update, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("update"), request);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("update"), "contextId",
i2pcontextId);

    // moved to java for ease of translation
    helper.renderSummaryBar();

      out.write('\n');
      out.write("\n  </div>\n");
      out.write('\n');

    } else {
        // Text browsers don't render the two divs side-by-side, so just provide a link
        out.print("<a href=\"/summaryframe\">");
        out.print(intl._t("Sidebar"));
        out.print("</a>");
    }

    // d and allowIFrame defined above
    if (false && !intl.getDisableRefresh()) {
        out.print("</div><noscript></iframe></noscript>\n");
    } else if (false && allowIFrame) {
        // since we don't have an iframe this will reload the base page, and
        // the new delay will be passed to the iframe above
        out.print("<noscript><div class=\"refresh\"><form action=\"" + request.getRequestURI() + "\" method=\"POST\">\n" +
                  "<b>");
        // We have intl defined when this is included, but not when compiled standalone.
        out.print(intl._t("Refresh (s)"));
        out.print(":</b> <input size=\"3\" type=\"text\" name=\"refresh\" value=\"60\" >\n" +
                  "<button type=\"submit\" value=\"Enable\" >");
        // ditto
        out.print(intl._t("Enable"));
        out.print("</button>\n" +
                  "</form></div></noscript></div>\n");
    } else {
        out.print("</div>\n");
    }

      out.write("\n</div>\n");
      out.write("\n<h1>");
      out.print(intl._t("I2P Router Logs"));
      out.write("</h1>\n<div class=\"main\" id=\"logs\">\n\n<table id=\"bugreports\"><tbody>\n  <tr><td class=\"infohelp\">\n");
      out.print(intl._t("Please include your I2P version and running environment information in bug reports"));
      out.write('.');
      out.write('\n');
      out.print(intl._t("Note that system information, log timestamps, and log messages may provide clues to your location; please review everything you include in a bug report."));
      out.write('\n');
 /* note to translators - both parameters are URLs */

      out.print(intl._t("Please report bugs on {0} or {1}.",
          "<a href=\"http://trac.i2p2.i2p/\">trac.i2p2.i2p</a>",
          "<a href=\"https://trac.i2p2.de/\">trac.i2p2.de</a>"));
      out.write("\n  </td></tr>\n</tbody></table>\n\n<h3 class=\"tabletitle\" id=\"version\">");
      out.print(intl._t("I2P Version and Running Environment"));
      out.write("</h3>\n<table id=\"enviro\"><tbody>\n<tr><td><!-- fix for first row not being selected --></td></tr>\n<tr><td><b>I2P version:</b></td><td>");
      out.print(net.i2p.router.RouterVersion.FULL_VERSION);
      out.write("</td></tr>\n<tr><td><b>Java version:</b></td><td>");
      out.print(System.getProperty("java.vendor"));
      out.write(' ');
      out.print(System.getProperty("java.version"));
      out.write(' ');
      out.write('(');
      out.print(System.getProperty("java.runtime.name"));
      out.write(' ');
      out.print(System.getProperty("java.runtime.version"));
      out.write(")</td></tr>\n ");
      net.i2p.router.web.helpers.LogsHelper logsHelper = null;
      logsHelper = (net.i2p.router.web.helpers.LogsHelper) _jspx_page_context.getAttribute("logsHelper", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (logsHelper == null){
        logsHelper = new net.i2p.router.web.helpers.LogsHelper();
        _jspx_page_context.setAttribute("logsHelper", logsHelper, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      out.write(' ');
      org.apache.jasper.runtime.JspRuntimeLibrary.handleSetProperty(_jspx_page_context.findAttribute("logsHelper"), "contextId",
i2pcontextId);
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((net.i2p.router.web.helpers.LogsHelper)_jspx_page_context.findAttribute("logsHelper")).getUnavailableCrypto())));
      out.write("\n<tr><td><b>Wrapper version:</b></td><td>");
      out.print(System.getProperty("wrapper.version", "none"));
      out.write("</td></tr>\n<tr><td><b>Server version:</b></td><td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((net.i2p.router.web.helpers.LogsHelper)_jspx_page_context.findAttribute("logsHelper")).getJettyVersion())));
      out.write("</td></tr>\n<tr><td><b>Servlet version:</b></td><td>");
      out.print(getServletInfo());
      out.write(' ');
      out.write('(');
      out.print(getServletConfig().getServletContext().getMajorVersion());
      out.write('.');
      out.print(getServletConfig().getServletContext().getMinorVersion());
      out.write(")</td></tr>\n<tr><td><b>JSTL version:</b></td><td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((net.i2p.router.web.helpers.LogsHelper)_jspx_page_context.findAttribute("logsHelper")).getJstlVersion())));
      out.write("</td></tr>\n<tr><td><b>Platform:</b></td><td>");
      out.print(System.getProperty("os.name"));
      out.write(' ');
      out.print(System.getProperty("os.arch"));
      out.write(' ');
      out.print(System.getProperty("os.version"));
      out.write("</td></tr>\n<tr><td><b>Processor:</b></td><td>\n");

   boolean isX86 = net.i2p.util.SystemVersion.isX86();
   if (isX86) {

      out.write(' ');
      out.print(net.i2p.util.NativeBigInteger.cpuModel());
      out.write('\n');

   }

      out.write(' ');
      out.write('(');
      out.print(net.i2p.util.NativeBigInteger.cpuType());
      out.write(")</td></tr>\n<tr><td><b>JBigI status:</b></td><td>");
      out.print(net.i2p.util.NativeBigInteger.loadStatus());
      out.write("</td></tr>\n<tr><td><b>GMP version:</b></td><td>");
      out.print(net.i2p.util.NativeBigInteger.getLibGMPVersion());
      out.write("</td></tr>\n<tr><td><b>JBigI version:</b></td><td>");
      out.print(net.i2p.util.NativeBigInteger.getJbigiVersion());
      out.write("</td></tr>\n");

   if (isX86) {

      out.write("<tr><td><b>JCpuId version:</b></td><td>");
      out.print(freenet.support.CPUInformation.CPUID.getJcpuidVersion());
      out.write("</td></tr>\n");

   }

      out.write("<tr><td><b>Encoding:</b></td><td>");
      out.print(System.getProperty("file.encoding"));
      out.write("</td></tr>\n<tr><td><b>Charset:</b></td><td>");
      out.print(java.nio.charset.Charset.defaultCharset().name());
      out.write("</td></tr>\n<tr><td><b>Built By:</b></td><td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((net.i2p.router.web.helpers.LogsHelper)_jspx_page_context.findAttribute("logsHelper")).getBuiltBy())));
      out.write("</tbody></table>\n\n<h3 class=\"tabletitle\">");
      out.print(intl._t("Critical Logs"));

    String consoleNonce = net.i2p.router.web.CSSHelper.getNonce();
    String ct1 = request.getParameter("clear");
    String ct2 = request.getParameter("crit");
    String ct3 = request.getParameter("svc");
    String ct4 = request.getParameter("svct");
    String ct5 = request.getParameter("svcf");
    String ctn = request.getParameter("consoleNonce");
    if ((ct1 != null || ct2 != null || (ct3 != null && ct4 != null && ct5 != null)) && ctn != null) {
        int ict1 = -1, ict2 = -1;
        long ict3 = -1, ict4 = -1;
        try { ict1 = Integer.parseInt(ct1); } catch (NumberFormatException nfe) {}
        try { ict2 = Integer.parseInt(ct2); } catch (NumberFormatException nfe) {}
        try { ict3 = Long.parseLong(ct3); } catch (NumberFormatException nfe) {}
        try { ict4 = Long.parseLong(ct4); } catch (NumberFormatException nfe) {}
        logsHelper.clearThrough(ict1, ict2, ict3, ict4, ct5, ctn);
    }
    int last = logsHelper.getLastCriticalMessageNumber();
    if (last >= 0) {

      out.write("&nbsp;<a class=\"delete\" title=\"");
      out.print(intl._t("Clear logs"));
      out.write("\" href=\"logs?crit=");
      out.print(last);
      out.write("&amp;consoleNonce=");
      out.print(consoleNonce);
      out.write('"');
      out.write('>');
      out.write('[');
      out.print(intl._t("Clear logs"));
      out.write("]</a>");

    }

      out.write("</h3>\n<table id=\"criticallogs\" class=\"logtable\"><tbody>\n<tr><td>\n ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((net.i2p.router.web.helpers.LogsHelper)_jspx_page_context.findAttribute("logsHelper")).getCriticalLogs())));
      out.write("\n</td></tr>\n</tbody></table>\n\n<h3 class=\"tabletitle\">");
      out.print(intl._t("Router Logs"));

    // both links float right, so first one goes last
    last = logsHelper.getLastMessageNumber();
    if (last >= 0) {

      out.write("&nbsp;<a class=\"delete\" title=\"");
      out.print(intl._t("Clear logs"));
      out.write("\" href=\"logs?clear=");
      out.print(last);
      out.write("&amp;consoleNonce=");
      out.print(consoleNonce);
      out.write('"');
      out.write('>');
      out.write('[');
      out.print(intl._t("Clear logs"));
      out.write("]</a>");

    }

      out.write("&nbsp;<a class=\"configure\" title=\"");
      out.print(intl._t("Configure router logging options"));
      out.write("\" href=\"configlogging\">[");
      out.print(intl._t("Configure"));
      out.write("]</a>\n</h3>\n<table id=\"routerlogs\" class=\"logtable\"><tbody>\n<tr><td>\n ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((net.i2p.router.web.helpers.LogsHelper)_jspx_page_context.findAttribute("logsHelper")).getLogs())));
      out.write("\n</td></tr>\n</tbody></table>\n\n<h3 class=\"tabletitle\">");
      out.print(intl._t("Event Logs"));
      out.write("</h3>\n<table id=\"eventlogs\" class=\"logtable\"><tbody>\n<tr><td>\n <!-- 90 days --><p><a href=\"events?from=7776000\">");
      out.print(intl._t("View event logs"));
      out.write("</a></p>\n</td></tr>\n</tbody></table>\n\n<h3 class=\"tabletitle\" id=\"servicelogs\">");
      out.print(intl._t("Service (Wrapper) Logs"));

    StringBuilder buf = new StringBuilder(24*1024);
    // timestamp, last line number, escaped filename
    Object[] vals = logsHelper.getServiceLogs(buf);
    String lts = vals[0].toString();
    long llast = ((Long) vals[1]).longValue();
    String filename = vals[2].toString();
    if (llast >= 0) {

      out.write("&nbsp;<a class=\"delete\" title=\"");
      out.print(intl._t("Clear logs"));
      out.write("\" href=\"logs?svc=");
      out.print(llast);
      out.write("&amp;svct=");
      out.print(lts);
      out.write("&amp;svcf=");
      out.print(filename);
      out.write("&amp;consoleNonce=");
      out.print(consoleNonce);
      out.write('"');
      out.write('>');
      out.write('[');
      out.print(intl._t("Clear logs"));
      out.write("]</a>");

    }

      out.write("</h3>\n<table id=\"wrapperlogs\" class=\"logtable\"><tbody>\n<tr><td>\n");

    out.append(buf);

      out.write("\n</td></tr>\n</tbody></table>\n</div></body></html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
